services:
  deltachat_publish:
    build: .
    container_name: deltachat_publish
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./data/publishbot:/root/.config/publishbot
    env_file:
      - .env
